name: Main Workflow
on: [push]
jobs:
  build:
    name: Run NosyMouse tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install NosyMouse CLI
        run: |
          curl https://github.com/nosymouse/CLI/blob/63881c560399a44508414d7a68ba2497a3f8f529/nosymouse-linux-x64.zip -L | unzip -q nosymouse-linux-x64.zip
      - name: Give rights to execute
        run: |
          chmod 777 *
      - name: run NosyMouse tests against dev
        run: |
          ./nosymouse -action:run -pat:"2mjDoABTbk+WHZWZH0CG" -projectId:"df9cbf4f-7c81-4537-9b5b-3ca74c200e7f" -scenarioId:"9e6845b3-3fb3-4590-85e3-84b08c29146e" -env:"dev" -url:"https://app.nosymouse.io"
